services:
  api:
    container_name: service-api
    build:
      context: .
    ports:
      - "${PORT:-3000}:3000"
    environment:
      DATABASE_URL: "postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@database:5432/${DATABASE_NAME}?schema=public"
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: service-database
    image: postgres:15-alpine
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ${DATABASE_VOLUME:-./pg_data}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DATABASE_USERNAME} -d $${DATABASE_NAME} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
